[build]
  command = "npm run build:netlify"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  VITE_SUPABASE_URL = "https://dubqlbhbthqwaqojcbwe.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1YnFsYmhidGhxd2Fxb2pjYndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjE1MzMsImV4cCI6MjA3NDEzNzUzM30.DluC7TMLtOEj7L-oJSa0PzaT-t0uCn1GMxoSOzHgZhM"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.api]
  runtime = "nodejs18.x"

[functions.test]
  runtime = "nodejs18.x"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200